services:
  - type: web
    name: appointment-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn appointment_backend.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: django-insecure-e3=38h)xn+dr_w!6@w*p@gwbzku8ahi$vt7ewak7ng76m$$8ca
      - key: DATABASE_URL
        fromDatabase:
          name: appointment-db
          property: connectionString
